/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppVersion: typeof import('./src/components/AppVersion/AppVersion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleClock: typeof import('./src/components/SimpleClock/SimpleClock.vue')['default']
    SimpleCounter: typeof import('./src/components/SimpleCounter/SimpleCounter.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/UserInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanRow: typeof import('vant/es')['Row']
  }
}
